services:
  mysql:
    restart: always
    image: mysql:oracle
    environment:
      - MYSQL_DATABASE=fileservicedb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 20
  app:
    build: ./
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8080:8080
  prometheus:
    image: prom/prometheus
    depends_on:
      - app
    ports:
      - 9090:9090
    command: --config.file=/etc/prometheus/config.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/config.yml
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
